# -*- coding: utf-8 -*-
#
# GPL License and Copyright Notice ============================================
#  This file is part of Wrye Bash.
#
#  Wrye Bash is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  Wrye Bash is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Wrye Bash; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#  Wrye Bash copyright (C) 2005-2009 Wrye, 2010-2019 Wrye Bash Team
#  https://github.com/wrye-bash
#
# =============================================================================

#--Game ESM/ESP/BSA files
#  These filenames need to be in lowercase,
bethDataFiles = {
    #--Vanilla
    u'e - meshes.bsa',
    u'e - music.bsa',
    u'e - scripts.bsa',
    u'e - sounds.bsa',
    u'e - textures1.bsa',
    u'e - textures2.bsa',
    u'e - textures3.bsa',
    u'enderal - forgotten stories.esm',
    u'l - textures.bsa',
    u'l - voices.bsa',
    u'skyrim - animations.bsa',
    u'skyrim - interface.bsa',
    u'skyrim - meshes.bsa',
    u'skyrim - misc.bsa',
    u'skyrim - shaders.bsa',
    u'skyrim - sounds.bsa',
    u'skyrim - textures.bsa',
    u'skyrim.esm',
    u'update.bsa',
    u'update.esm',
}

#--Every file in the Data directory from Bethsoft
allBethFiles = {
    # Section 1: Vanilla files
    u'E - Meshes.bsa',
    u'E - Music.bsa',
    u'E - Scripts.bsa',
    u'E - Sounds.bsa',
    u'E - Textures1.bsa',
    u'E - Textures2.bsa',
    u'E - Textures3.bsa',
    u'Enderal - Forgotten Stories.esm',
    u'L - Textures.bsa',
    u'L - Voices.bsa',
    u'Skyrim - Animations.bsa',
    u'Skyrim - Interface.bsa',
    u'Skyrim - Meshes.bsa',
    u'Skyrim - Misc.bsa',
    u'Skyrim - Shaders.bsa',
    u'Skyrim - Sounds.bsa',
    u'Skyrim - Textures.bsa',
    u'Skyrim.esm',
    u'Update.bsa',
    u'Update.esm',
    u'Interface\\00E_heromenu.swf',
    u'Interface\\00E_statsmenu.swf',
    u'Interface\\bartermenu.swf',
    u'Interface\\book.swf',
    u'Interface\\bookmenu.swf',
    u'Interface\\console.swf',
    u'Interface\\console_alias.ini',
    u'Interface\\containermenu.swf',
    u'Interface\\controls',
    u'Interface\\cosmeticmenu.swf',
    u'Interface\\craftingmenu.swf',
    u'Interface\\credits.txt',
    u'Interface\\creditsmenu.swf',
    u'Interface\\cursormenu.swf',
    u'Interface\\dialoguemenu.swf',
    u'Interface\\dyemenu.swf',
    u'Interface\\exported',
    u'Interface\\extension_assets',
    u'Interface\\fadermenu.swf',
    u'Interface\\favoritesmenu.swf',
    u'Interface\\fontconfig.txt',
    u'Interface\\fonts_console.swf',
    u'Interface\\fonts_en.swf',
    u'Interface\\fonts_en2.swf',
    u'Interface\\fonts_fh2.swf',
    u'Interface\\giftmenu.swf',
    u'Interface\\inventorymenu.swf',
    u'Interface\\levelupmenu.swf',
    u'Interface\\listmenu.swf',
    u'Interface\\loadingmenu.swf',
    u'Interface\\lockpickingmenu.swf',
    u'Interface\\magicmenu.swf',
    u'Interface\\magicmenuext.swf',
    u'Interface\\magic_card_2.swf',
    u'Interface\\map.swf',
    u'Interface\\messagebox.swf',
    u'Interface\\quest_journal.swf',
    u'Interface\\selectionmenu.swf',
    u'Interface\\sharedcomponents.swf',
    u'Interface\\skyui',
    u'Interface\\sleepwaitmenu.swf',
    u'Interface\\startmenu.swf',
    u'Interface\\statsmenu.swf',
    u'Interface\\statssheetmenu.swf',
    u'Interface\\textentrymenu.swf',
    u'Interface\\titles.swf',
    u'Interface\\trainingmenu.swf',
    u'Interface\\Translate_ENGLISH.txt',
    u'Interface\\translations',
    u'Interface\\tweenmenu.swf',
    u'Interface\\wheelmenu.swf',
    u'Interface\\widgetoverlay.swf',
    u'Interface\\controls\\360\\controlmap.txt',
    u'Interface\\controls\\360\\gamepad.txt',
    u'Interface\\controls\\360\\keyboard_english.txt',
    u'Interface\\controls\\pc\\controlmap.txt',
    u'Interface\\controls\\pc\\gamepad.txt',
    u'Interface\\controls\\pc\\keyboard_english.txt',
    u'Interface\\controls\\pc\\keyboard_french.txt',
    u'Interface\\controls\\pc\\keyboard_german.txt',
    u'Interface\\controls\\pc\\keyboard_italian.txt',
    u'Interface\\controls\\pc\\keyboard_spanish.txt',
    u'Interface\\controls\\pc\\mouse.txt',
    u'Interface\\controls\\ps3\\controlmap.txt',
    u'Interface\\controls\\ps3\\gamepad.txt',
    u'Interface\\controls\\ps3\\keyboard_english.txt',
    u'Interface\\exported\\0.png.dds',
    u'Interface\\exported\\1.png.dds',
    u'Interface\\exported\\2.png.dds',
    u'Interface\\exported\\3.png.dds',
    u'Interface\\exported\\360_a.png.dds',
    u'Interface\\exported\\360_b.png.dds',
    u'Interface\\exported\\360_back.png.dds',
    u'Interface\\exported\\360_l3.png.dds',
    u'Interface\\exported\\360_lb.png.dds',
    u'Interface\\exported\\360_ls.png.dds',
    u'Interface\\exported\\360_lt.png.dds',
    u'Interface\\exported\\360_ltrt.png.dds',
    u'Interface\\exported\\360_r3.png.dds',
    u'Interface\\exported\\360_rb.png.dds',
    u'Interface\\exported\\360_rs.png.dds',
    u'Interface\\exported\\360_rt.png.dds',
    u'Interface\\exported\\360_start.png.dds',
    u'Interface\\exported\\360_x.png.dds',
    u'Interface\\exported\\360_y.png.dds',
    u'Interface\\exported\\4.png.dds',
    u'Interface\\exported\\5.png.dds',
    u'Interface\\exported\\6.png.dds',
    u'Interface\\exported\\7.png.dds',
    u'Interface\\exported\\8.png.dds',
    u'Interface\\exported\\9.png.dds',
    u'Interface\\exported\\a.png.dds',
    u'Interface\\exported\\b.png.dds',
    u'Interface\\exported\\backslash.png.dds',
    u'Interface\\exported\\backspace.png.dds',
    u'Interface\\exported\\bracketleft.png.dds',
    u'Interface\\exported\\bracketright.png.dds',
    u'Interface\\exported\\c.png.dds',
    u'Interface\\exported\\capslock.png.dds',
    u'Interface\\exported\\comma.png.dds',
    u'Interface\\exported\\d.png.dds',
    u'Interface\\exported\\diamondmarker.dds',
    u'Interface\\exported\\down.png.dds',
    u'Interface\\exported\\e.png.dds',
    u'Interface\\exported\\enter.png.dds',
    u'Interface\\exported\\equal.png.dds',
    u'Interface\\exported\\esc.png.dds',
    u'Interface\\exported\\f.png.dds',
    u'Interface\\exported\\f1.png.dds',
    u'Interface\\exported\\f10.png.dds',
    u'Interface\\exported\\f11.png.dds',
    u'Interface\\exported\\f12.png.dds',
    u'Interface\\exported\\f2.png.dds',
    u'Interface\\exported\\f3.png.dds',
    u'Interface\\exported\\f4.png.dds',
    u'Interface\\exported\\f5.png.dds',
    u'Interface\\exported\\f6.png.dds',
    u'Interface\\exported\\f7.png.dds',
    u'Interface\\exported\\f8.png.dds',
    u'Interface\\exported\\f9.png.dds',
    u'Interface\\exported\\g.png.dds',
    u'Interface\\exported\\h.png.dds',
    u'Interface\\exported\\hudmenu.gfx',
    u'Interface\\exported\\hudmenu_i29e.dds',
    u'Interface\\exported\\hudmenu_i2a1.dds',
    u'Interface\\exported\\hudmenu_i2a7.dds',
    u'Interface\\exported\\hudmenu_i2aa.dds',
    u'Interface\\exported\\hudmenu_i2bb.dds',
    u'Interface\\exported\\hudmenu_i2c1.dds',
    u'Interface\\exported\\hudmenu_i2c7.dds',
    u'Interface\\exported\\hudmenu_i2cd.dds',
    u'Interface\\exported\\hyphen.png.dds',
    u'Interface\\exported\\i.png.dds',
    u'Interface\\exported\\j.png.dds',
    u'Interface\\exported\\k.png.dds',
    u'Interface\\exported\\l-alt.png.dds',
    u'Interface\\exported\\l-ctrl.png.dds',
    u'Interface\\exported\\l-shift.png.dds',
    u'Interface\\exported\\l.png.dds',
    u'Interface\\exported\\left.png.dds',
    u'Interface\\exported\\m.png.dds',
    u'Interface\\exported\\m1m2.png.dds',
    u'Interface\\exported\\mouse.png.dds',
    u'Interface\\exported\\mouse1.png.dds',
    u'Interface\\exported\\mouse2.png.dds',
    u'Interface\\exported\\mouse3.png.dds',
    u'Interface\\exported\\mouse4.png.dds',
    u'Interface\\exported\\mouse5.png.dds',
    u'Interface\\exported\\mouse6.png.dds',
    u'Interface\\exported\\mouse7.png.dds',
    u'Interface\\exported\\mouse8.png.dds',
    u'Interface\\exported\\mousemove.png.dds',
    u'Interface\\exported\\n.png.dds',
    u'Interface\\exported\\o.png.dds',
    u'Interface\\exported\\p.png.dds',
    u'Interface\\exported\\period.png.dds',
    u'Interface\\exported\\ps3_a.png.dds',
    u'Interface\\exported\\ps3_b.png.dds',
    u'Interface\\exported\\ps3_back.png.dds',
    u'Interface\\exported\\ps3_l3.png.dds',
    u'Interface\\exported\\ps3_lb.png.dds',
    u'Interface\\exported\\ps3_lbrb.png.dds',
    u'Interface\\exported\\ps3_ls.png.dds',
    u'Interface\\exported\\ps3_lt.png.dds',
    u'Interface\\exported\\ps3_ltrt.png.dds',
    u'Interface\\exported\\ps3_r3.png.dds',
    u'Interface\\exported\\ps3_rb.png.dds',
    u'Interface\\exported\\ps3_rs.png.dds',
    u'Interface\\exported\\ps3_rt.png.dds',
    u'Interface\\exported\\ps3_start.png.dds',
    u'Interface\\exported\\ps3_x.png.dds',
    u'Interface\\exported\\ps3_y.png.dds',
    u'Interface\\exported\\q.png.dds',
    u'Interface\\exported\\quest_journal.gfx',
    u'Interface\\exported\\quotesingle.png.dds',
    u'Interface\\exported\\r-alt.png.dds',
    u'Interface\\exported\\r-ctrl.png.dds',
    u'Interface\\exported\\r-shift.png.dds',
    u'Interface\\exported\\r.png.dds',
    u'Interface\\exported\\racesex_menu.gfx',
    u'Interface\\exported\\right.png.dds',
    u'Interface\\exported\\s.png.dds',
    u'Interface\\exported\\safezone.gfx',
    u'Interface\\exported\\semicolon.png.dds',
    u'Interface\\exported\\skyui',
    u'Interface\\exported\\slash.png.dds',
    u'Interface\\exported\\space.png.dds',
    u'Interface\\exported\\t.png.dds',
    u'Interface\\exported\\tab.png.dds',
    u'Interface\\exported\\textentry.gfx',
    u'Interface\\exported\\tilde.png.dds',
    u'Interface\\exported\\tutorialmenu.gfx',
    u'Interface\\exported\\u.png.dds',
    u'Interface\\exported\\up.png.dds',
    u'Interface\\exported\\v.png.dds',
    u'Interface\\exported\\w.png.dds',
    u'Interface\\exported\\widgets',
    u'Interface\\exported\\x.png.dds',
    u'Interface\\exported\\y.png.dds',
    u'Interface\\exported\\z.png.dds',
    u'Interface\\exported\\skyui\\icons_effect_psychosteve.swf',
    u'Interface\\exported\\skyui\\widgetloader.swf',
    u'Interface\\exported\\uilib\\uilib_1_notificationarea.swf',
    u'Interface\\exported\\widgets\\skyui',
    u'Interface\\exported\\widgets\\skyui\\activeeffects.swf',
    u'Interface\\exported\\widgets\\skyui\\followerpanel.swf',
    u'Interface\\exported\\widgets\\skyui\\meter.swf',
    u'Interface\\extension_assets\\bottombar.swf',
    u'Interface\\extension_assets\\buttonart.swf',
    u'Interface\\extension_assets\\icons_category_psychosteve.swf',
    u'Interface\\extension_assets\\meter.swf',
    u'Interface\\skyui\\bottombar.swf',
    u'Interface\\skyui\\buttonart.swf',
    u'Interface\\skyui\\config.txt',
    u'Interface\\skyui\\configpanel.swf',
    u'Interface\\skyui\\icons_category_celtic.swf',
    u'Interface\\skyui\\icons_category_curved.swf',
    u'Interface\\skyui\\icons_category_psychosteve.swf',
    u'Interface\\skyui\\icons_category_straight.swf',
    u'Interface\\skyui\\icons_item_psychosteve.swf',
    u'Interface\\skyui\\inventorylists.swf',
    u'Interface\\skyui\\itemcard.swf',
    u'Interface\\skyui\\mapmarkerart.swf',
    u'Interface\\skyui\\mcm_splash.swf',
    u'Interface\\skyui\\skyui_splash.swf',
    u'Interface\\skyui\\res\\mcm_logo.dds',
    u'Interface\\translations\\buriedtreasure_english.txt',
    u'Interface\\translations\\skyui_czech.txt',
    u'Interface\\translations\\skyui_english.txt',
    u'Interface\\translations\\skyui_french.txt',
    u'Interface\\translations\\skyui_german.txt',
    u'Interface\\translations\\skyui_italian.txt',
    u'Interface\\translations\\skyui_japanese.txt',
    u'Interface\\translations\\skyui_polish.txt',
    u'Interface\\translations\\skyui_russian.txt',
    u'Interface\\translations\\skyui_spanish.txt',
    u'Interface\\translations\\taverngamesczech.txt',
    u'Interface\\translations\\taverngames_english.txt',
    u'Interface\\translations\\taverngames_french.txt',
    u'Interface\\translations\\taverngames_german.txt',
    u'Interface\\translations\\taverngames_italian.txt',
    u'Interface\\translations\\taverngames_japanese.txt',
    u'Interface\\translations\\taverngames_polish.txt',
    u'Interface\\translations\\taverngames_russian.txt',
    u'Interface\\translations\\taverngames_spanish.txt',
    u'Interface\\translations\\uiextensions_english.txt',
    u'Interface\\translations\\uiextensions_german.txt',
    u'Interface\\uilib\\buttonart.swf',
    u'Interface\\uilib\\uilib_1_listmenu.swf',
    u'Interface\\uilib\\uilib_1_textinputmenu.swf',
    u'Meshes\\Actors',
    u'Meshes\\animationdatasinglefile.txt',
    u'Meshes\\animationsetdatasinglefile.txt',
    u'Meshes\\Actors\\character',
    u'Meshes\\Actors\\character\\behaviors',
    u'Meshes\\Actors\\character\\characters',
    u'Meshes\\Actors\\character\\characters female',
    u'Meshes\\Actors\\character\\behaviors\\0_master.hkx',
    u'Meshes\\Actors\\character\\behaviors\\1hm_behavior.hkx',
    u'Meshes\\Actors\\character\\behaviors\\FNIS_Enderal_Behavior.hkx',
    u'Meshes\\Actors\\character\\behaviors\\FNIS_FNISBase_Behavior.hkx',
    u'Meshes\\Actors\\character\\behaviors\\FNIS_PaleTest04_Behavior.hkx',
    u'Meshes\\Actors\\character\\behaviors\\FNIS_PipeSmoking_Behavior.hkx',
    u'Meshes\\Actors\\character\\behaviors\\magicbehavior.hkx',
    u'Meshes\\Actors\\character\\behaviors\\mt_behavior.hkx',
    u'Meshes\\Actors\\character\\behaviors\\sprintbehavior - Kopie.hkx',
    u'Meshes\\Actors\\character\\behaviors\\sprintbehavior.hkx',
    u'Meshes\\Actors\\character\\characters\\defaultmale.hkx',
    u'Meshes\\Actors\\character\\characters female\\defaultfemale.hkx',
    # Section 2: SKSE Files
    u'SKSE\\Plugins',
    u'SKSE\\SKSE.ini',
    u'SKSE\\Plugins\\AHZmoreHUDPlugin.dll',
    u'SKSE\\Plugins\\CharGen',
    u'SKSE\\Plugins\\CrashFixPlugin.dll',
    u'SKSE\\Plugins\\CrashFixPlugin.ini',
    u'SKSE\\Plugins\\CrashLog',
    u'SKSE\\Plugins\\flat_map_markers.dll',
    u'SKSE\\Plugins\\flat_map_markers.ini',
    u'SKSE\\Plugins\\fs.dll',
    u'SKSE\\Plugins\\InsertAttackData.dll',
    u'SKSE\\Plugins\\JCData',
    u'SKSE\\Plugins\\JContainers.dll',
    u'SKSE\\Plugins\\LipSyncFix.dll',
    u'SKSE\\Plugins\\MDX_NoPoisonDialogs.dll',
    u'SKSE\\Plugins\\MfgConsole.dll',
    u'SKSE\\Plugins\\MfgConsole.ini',
    u'SKSE\\Plugins\\OneTweak.dll',
    u'SKSE\\Plugins\\OneTweak.ini',
    u'SKSE\\Plugins\\SkyrimRedirector.dll',
    u'SKSE\\Plugins\\Source',
    u'SKSE\\Plugins\\StorageUtil.dll',
    u'SKSE\\Plugins\\StorageUtilData',
    u'SKSE\\Plugins\\tkplugin.dll',
    u'SKSE\\Plugins\\CharGen\\Jespar.dds',
    u'SKSE\\Plugins\\CharGen\\Jespar.nif',
    u'SKSE\\Plugins\\JCData\\Domains',
    u'SKSE\\Plugins\\JCData\\InternalLuaScripts',
    u'SKSE\\Plugins\\JCData\\lua',
    u'SKSE\\Plugins\\JCData\\Domains\\JContainers_DomainExample',
    u'SKSE\\Plugins\\JCData\\Domains\\JContainers_DomainExample\\dummy-file',
    u'SKSE\\Plugins\\JCData\\InternalLuaScripts\\api_for_lua.h',
    u'SKSE\\Plugins\\JCData\\InternalLuaScripts\\init.lua',
    u'SKSE\\Plugins\\JCData\\InternalLuaScripts\\jc.lua',
    u'SKSE\\Plugins\\JCData\\lua\\jc',
    u'SKSE\\Plugins\\JCData\\lua\\testing',
    u'SKSE\\Plugins\\JCData\\lua\\jc\\init.lua',
    u'SKSE\\Plugins\\JCData\\lua\\testing\\basic.lua',
    u'SKSE\\Plugins\\JCData\\lua\\testing\\init.lua',
    u'SKSE\\Plugins\\JCData\\lua\\testing\\jc-tests.lua',
    u'SKSE\\Plugins\\JCData\\lua\\testing\\misc.lua',
    u'SKSE\\Plugins\\JCData\\lua\\testing\\test.lua',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\forgotten_stories_skse_plugin.sln',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\phasmalist_skse_plugin.VC.db',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skaar_skse_plugin.VC.db',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\common.vcxproj',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IArchive.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IArchive.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IBufferStream.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IBufferStream.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IConsole.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IConsole.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ICriticalSection.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDatabase.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDatabase.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDatabase.inc',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDataStream.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDataStream.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDebugLog.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDebugLog.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDirectoryIterator.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDirectoryIterator.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDynamicCreate.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IDynamicCreate.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IErrors.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IErrors.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IEvent.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IEvent.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IFIFO.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IFIFO.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IFileStream.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IFileStream.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IInterlockedLong.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IInterlockedLong.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ILinkedList.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IMemPool.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IMemPool.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IMutex.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IMutex.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IPipeClient.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IPipeClient.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IPipeServer.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IPipeServer.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IPrefix.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IPrefix.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IRangeMap.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IRangeMap.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IReadWriteLock.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IReadWriteLock.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ISegmentStream.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ISegmentStream.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ISingleton.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ISingleton.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ITextParser.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ITextParser.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IThread.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\IThread.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ITimer.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ITimer.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ITypes.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\common\\ITypes.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\Achievements.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\Achievements.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\CreatePotion.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\CreatePotion.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\exports.def',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\fs.vcxproj',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\main.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\PhasmalistInventoryFunctions.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\fs\\PhasmalistInventoryFunctions.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Colors.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Colors.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\CommandTable.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\CommandTable.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\CustomMenu.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\CustomMenu.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\exports.def',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameAPI.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameAPI.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameBSExtraData.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameCamera.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameCamera.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameData.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameData.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameEvents.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameEvents.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameExtraData.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameExtraData.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameFormComponents.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameFormComponents.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameForms.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameForms.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameHandlers.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameHandlers.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameInput.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameInput.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameMenus.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameMenus.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameObjects.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameObjects.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GamePathing.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GamePathing.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameReferences.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameReferences.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameResources.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameResources.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameRTTI.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameRTTI.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameSettings.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameSettings.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameStreams.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameStreams.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameThreads.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameThreads.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameTypes.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GameTypes.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GlobalLocks.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\GlobalLocks.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\HashUtil.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\HashUtil.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Camera.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Camera.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Debug.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Debug.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_DirectInput8Create.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_DirectInput8Create.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Event.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Event.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Gameplay.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Gameplay.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Handlers.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Handlers.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Memory.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Memory.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_NetImmerse.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_NetImmerse.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_ObScript.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_ObScript.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Papyrus.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Papyrus.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_SaveLoad.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_SaveLoad.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Scaleform.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Scaleform.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Threads.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_Threads.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_UI.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Hooks_UI.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\InputMap.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\InputMap.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\InternalSerialization.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\InternalSerialization.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiControllers.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiControllers.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiExtraData.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiExtraData.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiGeometry.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiGeometry.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiInterpolators.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiInterpolators.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiLight.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiLight.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiMaterial.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiMaterial.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiNodes.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiNodes.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiObjects.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiObjects.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiProperties.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiProperties.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiRenderer.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiRenderer.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiRTTI.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiRTTI.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiSerialization.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiSerialization.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiTextures.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiTextures.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiTypes.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\NiTypes.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusActiveMagicEffect.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusActiveMagicEffect.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusActor.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusActor.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusActorBase.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusActorBase.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusActorValueInfo.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusActorValueInfo.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusAlias.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusAlias.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusAmmo.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusAmmo.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusArgs.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusArgs.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusArmor.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusArmor.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusArmorAddon.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusArmorAddon.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusArt.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusArt.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusBook.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusBook.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusCell.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusCell.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusClass.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusClass.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusColorForm.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusColorForm.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusCombatStyle.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusCombatStyle.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusConstructibleObject.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusConstructibleObject.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusDefaultObjectManager.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusDefaultObjectManager.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusEnchantment.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusEnchantment.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusEquipSlot.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusEquipSlot.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusEvents.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusEvents.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusFlora.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusFlora.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusForm.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusForm.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusGame.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusGame.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusHeadPart.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusHeadPart.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusIngredient.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusIngredient.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusInput.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusInput.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusKeyword.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusKeyword.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusLeveledActor.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusLeveledActor.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusLeveledItem.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusLeveledItem.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusLeveledSpell.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusLeveledSpell.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusMagicEffect.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusMagicEffect.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusMath.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusMath.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusMisc.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusMisc.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusModEvent.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusModEvent.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusNativeFunctionDef.inl',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusNativeFunctionDef_Base.inl',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusNativeFunctions.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusNativeFunctions.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusNetImmerse.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusNetImmerse.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusObjectReference.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusObjectReference.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusObjects.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusObjects.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusPerk.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusPerk.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusPotion.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusPotion.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusQuest.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusQuest.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusRace.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusRace.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusScroll.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusScroll.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusShout.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusShout.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusSKSE.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusSKSE.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusSound.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusSound.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusSoundDescriptor.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusSoundDescriptor.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusSpell.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusSpell.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusStringUtil.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusStringUtil.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusTextureSet.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusTextureSet.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusTree.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusTree.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusUI.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusUI.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusUICallback.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusUICallback.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusUtility.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusUtility.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusVM.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusVM.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusWeapon.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusWeapon.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusWeather.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusWeather.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusWornObject.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PapyrusWornObject.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PluginAPI.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PluginManager.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\PluginManager.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\SafeWrite.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\SafeWrite.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformAPI.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformAPI.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformCallbacks.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformCallbacks.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformExtendedData.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformExtendedData.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformLoader.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformLoader.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformMovie.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformMovie.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformState.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformState.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformTypes.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformTypes.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformVM.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\ScaleformVM.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Serialization.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Serialization.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\skse.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\skse.vcxproj',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\skse_license.txt',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\skse_version.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\skse_version.rc',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Translation.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Translation.h',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Utilities.cpp',
    u'SKSE\\Plugins\\Source\\fs_skse_plugin\\skse\\Utilities.h',
    # Section 3: Strings Files
    u'Strings\\Enderal - Forgotten Stories_english.DLSTRINGS',
    u'Strings\\Enderal - Forgotten Stories_english.ILSTRINGS',
    u'Strings\\Enderal - Forgotten Stories_english.STRINGS',
    u'Strings\\Skyrim_english.DLSTRINGS',
    u'Strings\\Skyrim_English.ILSTRINGS',
    u'Strings\\Skyrim_English.STRINGS',
    # Section 4: Video Clips
    u'Video\\EnderalIntro.bik',
    u'Video\\Enderal_Credits.bik',
    u'Video\\MQ17BlackGuardian.bik',
    u'Video\\MQP03NearDeathExperience.bik',
}

# Function Info ---------------------------------------------------------------
conditionFunctionData = ( #--0: no param; 1: int param; 2: formid param; 3: float param
    (  0, 'GetWantBlocking', 0, 0, 0),
    (  1, 'GetDistance', 2, 0, 0),
    (  5, 'GetLocked', 0, 0, 0),
    (  6, 'GetPos', 0, 0, 0),
    (  8, 'GetAngle', 0, 0, 0),
    ( 10, 'GetStartingPos', 0, 0, 0),
    ( 11, 'GetStartingAngle', 0, 0, 0),
    ( 12, 'GetSecondsPassed', 0, 0, 0),
    ( 14, 'GetValue', 2, 0, 0),
    ( 18, 'GetCurrentTime', 0, 0, 0),
    ( 24, 'GetScale', 0, 0, 0),
    ( 25, 'IsMoving', 0, 0, 0),
    ( 26, 'IsTurning', 0, 0, 0),
    ( 27, 'GetLineOfSight', 2, 0, 0),
    ( 32, 'GetInSameCell', 2, 0, 0),
    ( 35, 'GetDisabled', 0, 0, 0),
    ( 36, 'MenuMode', 1, 0, 0),
    ( 39, 'GetDisease', 0, 0, 0),
    ( 41, 'GetClothingValue', 0, 0, 0),
    ( 42, 'SameFaction', 2, 0, 0),
    ( 43, 'SameRace', 2, 0, 0),
    ( 44, 'SameSex', 2, 0, 0),
    ( 45, 'GetDetected', 2, 0, 0),
    ( 46, 'GetDead', 0, 0, 0),
    ( 47, 'GetItemCount', 2, 0, 0),
    ( 48, 'GetGold', 0, 0, 0),
    ( 49, 'GetSleeping', 0, 0, 0),
    ( 50, 'GetTalkedToPC', 0, 0, 0),
    ( 56, 'GetQuestRunning', 2, 0, 0),
    ( 58, 'GetStage', 2, 0, 0),
    ( 59, 'GetStageDone', 2, 1, 0),
    ( 60, 'GetFactionRankDifference', 2, 2, 0),
    ( 61, 'GetAlarmed', 0, 0, 0),
    ( 62, 'IsRaining', 0, 0, 0),
    ( 63, 'GetAttacked', 0, 0, 0),
    ( 64, 'GetIsCreature', 0, 0, 0),
    ( 65, 'GetLockLevel', 0, 0, 0),
    ( 66, 'GetShouldAttack', 2, 0, 0),
    ( 67, 'GetInCell', 2, 0, 0),
    ( 68, 'GetIsClass', 2, 0, 0),
    ( 69, 'GetIsRace', 2, 0, 0),
    ( 70, 'GetIsSex', 1, 0, 0),
    ( 71, 'GetInFaction', 2, 0, 0),
    ( 72, 'GetIsID', 2, 0, 0),
    ( 73, 'GetFactionRank', 2, 0, 0),
    ( 74, 'GetGlobalValue', 2, 0, 0),
    ( 75, 'IsSnowing', 0, 0, 0),
    ( 77, 'GetRandomPercent', 0, 0, 0),
    ( 79, 'WouldBeStealing', 2, 0, 0),
    ( 80, 'GetLevel', 0, 0, 0),
    ( 81, 'IsRotating', 0, 0, 0),
    ( 84, 'GetDeadCount', 2, 0, 0),
    ( 91, 'GetIsAlerted', 0, 0, 0),
    ( 98, 'GetPlayerControlsDisabled', 1, 1, 1),
    ( 99, 'GetHeadingAngle', 2, 0, 0),
    (101, 'IsWeaponMagicOut', 0, 0, 0),
    (102, 'IsTorchOut', 0, 0, 0),
    (103, 'IsShieldOut', 0, 0, 0),
    (106, 'IsFacingUp', 0, 0, 0),
    (107, 'GetKnockedState', 0, 0, 0),
    (108, 'GetWeaponAnimType', 0, 0, 0),
    (109, 'IsWeaponSkillType', 2, 0, 0),
    (110, 'GetCurrentAIPackage', 0, 0, 0),
    (111, 'IsWaiting', 0, 0, 0),
    (112, 'IsIdlePlaying', 0, 0, 0),
    (116, 'IsIntimidatedbyPlayer', 0, 0, 0),
    (117, 'IsPlayerInRegion', 2, 0, 0),
    (118, 'GetActorAggroRadiusViolated', 0, 0, 0),
    (122, 'GetCrime', 2, 1, 0),
    (123, 'IsGreetingPlayer', 0, 0, 0),
    (125, 'IsGuard', 0, 0, 0),
    (127, 'HasBeenEaten', 0, 0, 0),
    (128, 'GetStaminaPercentage', 0, 0, 0),
    (129, 'HasBeenRead', 0, 0, 0),
    (130, 'GetDying', 0, 0, 0),
    (131, 'GetSceneActionPercent', 2, 2, 0),
    (132, 'WouldRefuseCommand', 2, 0, 0),
    (133, 'SameFactionAsPC', 0, 0, 0),
    (134, 'SameRaceAsPC', 0, 0, 0),
    (135, 'SameSexAsPC', 0, 0, 0),
    (136, 'GetIsReference', 2, 0, 0),
    (141, 'IsTalking', 0, 0, 0),
    (142, 'GetComponentCount', 2, 0, 0),
    (143, 'GetCurrentAIProcedure', 0, 0, 0),
    (144, 'GetTrespassWarningLevel', 0, 0, 0),
    (145, 'IsTrespassing', 0, 0, 0),
    (146, 'IsInMyOwnedCell', 0, 0, 0),
    (147, 'GetWindSpeed', 0, 0, 0),
    (148, 'GetCurrentWeatherPercent', 0, 0, 0),
    (149, 'GetIsCurrentWeather', 2, 0, 0),
    (150, 'IsContinuingPackagePCNear', 0, 0, 0),
    (152, 'GetIsCrimeFaction', 2, 0, 0),
    (153, 'CanHaveFlames', 0, 0, 0),
    (154, 'HasFlames', 0, 0, 0),
    (157, 'GetOpenState', 0, 0, 0),
    (159, 'GetSitting', 0, 0, 0),
    (161, 'GetIsCurrentPackage', 2, 0, 0),
    (162, 'IsCurrentFurnitureRef', 2, 0, 0),
    (163, 'IsCurrentFurnitureObj', 2, 0, 0),
    (170, 'GetDayOfWeek', 0, 0, 0),
    (172, 'GetTalkedToPCParam', 2, 0, 0),
    (175, 'IsPCSleeping', 0, 0, 0),
    (176, 'IsPCAMurderer', 0, 0, 0),
    (180, 'HasSameEditorLocationAsRef', 2, 2, 0),
    (181, 'HasSameEditorLocationAsRefAlias', 0, 2, 0),
    (182, 'GetEquipped', 2, 0, 0),
    (185, 'IsSwimming', 0, 0, 0),
    (190, 'GetAmountSoldStolen', 0, 0, 0),
    (192, 'GetIgnoreCrime', 0, 0, 0),
    (193, 'GetPCExpelled', 2, 0, 0),
    (195, 'GetPCFactionMurder', 2, 0, 0),
    (197, 'GetPCEnemyofFaction', 2, 0, 0),
    (199, 'GetPCFactionAttack', 2, 0, 0),
    (203, 'GetDestroyed', 0, 0, 0),
    (214, 'HasMagicEffect', 2, 0, 0),
    (215, 'GetDefaultOpen', 0, 0, 0),
    (223, 'IsSpellTarget', 2, 0, 0),
    (224, 'GetVATSMode', 0, 0, 0),
    (225, 'GetPersuasionNumber', 0, 0, 0),
    (226, 'GetVampireFeed', 0, 0, 0),
    (227, 'GetCannibal', 0, 0, 0),
    (228, 'GetIsClassDefault', 2, 0, 0),
    (229, 'GetClassDefaultMatch', 0, 0, 0),
    (230, 'GetInCellParam', 2, 2, 0),
    (231, 'GetPlayerDialogueInput', 0, 0, 0),
    (235, 'GetVatsTargetHeight', 0, 0, 0),
    (237, 'GetIsGhost', 0, 0, 0),
    (242, 'GetUnconscious', 0, 0, 0),
    (244, 'GetRestrained', 0, 0, 0),
    (246, 'GetIsUsedItem', 2, 0, 0),
    (247, 'GetIsUsedItemType', 2, 0, 0),
    (248, 'IsScenePlaying', 2, 0, 0),
    (249, 'IsInDialogueWithPlayer', 0, 0, 0),
    (250, 'GetLocationCleared', 2, 0, 0),
    (254, 'GetIsPlayableRace', 0, 0, 0),
    (255, 'GetOffersServicesNow', 0, 0, 0),
    (258, 'HasAssociationType', 2, 0, 0),
    (259, 'HasFamilyRelationship', 2, 0, 0),
    (261, 'HasParentRelationship', 2, 0, 0),
    (262, 'IsWarningAbout', 2, 0, 0),
    (263, 'IsWeaponOut', 0, 0, 0),
    (264, 'HasSpell', 2, 0, 0),
    (265, 'IsTimePassing', 0, 0, 0),
    (266, 'IsPleasant', 0, 0, 0),
    (267, 'IsCloudy', 0, 0, 0),
    (274, 'IsSmallBump', 0, 0, 0),
    (277, 'GetBaseValue', 2, 0, 0),
    (278, 'IsOwner', 2, 0, 0),
    (280, 'IsCellOwner', 2, 2, 0),
    (282, 'IsHorseStolen', 0, 0, 0),
    (285, 'IsLeftUp', 0, 0, 0),
    (286, 'IsSneaking', 0, 0, 0),
    (287, 'IsRunning', 0, 0, 0),
    (288, 'GetFriendHit', 0, 0, 0),
    (289, 'IsInCombat', 1, 0, 0),
    (300, 'IsInInterior', 0, 0, 0),
    (304, 'IsWaterObject', 0, 0, 0),
    (305, 'GetPlayerAction', 0, 0, 0),
    (306, 'IsActorUsingATorch', 0, 0, 0),
    (309, 'IsXBox', 0, 0, 0),
    (310, 'GetInWorldspace', 2, 0, 0),
    (312, 'GetPCMiscStat', 0, 0, 0),
    (313, 'GetPairedAnimation', 0, 0, 0),
    (314, 'IsActorAVictim', 0, 0, 0),
    (315, 'GetTotalPersuasionNumber', 0, 0, 0),
    (318, 'GetIdleDoneOnce', 0, 0, 0),
    (320, 'GetNoRumors', 0, 0, 0),
    (323, 'GetCombatState', 0, 0, 0),
    (325, 'GetWithinPackageLocation', 2, 0, 0),
    (327, 'IsRidingMount', 0, 0, 0),
    (329, 'IsFleeing', 0, 0, 0),
    (332, 'IsInDangerousWater', 0, 0, 0),
    (338, 'GetIgnoreFriendlyHits', 0, 0, 0),
    (339, 'IsPlayersLastRiddenMount', 0, 0, 0),
    (353, 'IsActor', 0, 0, 0),
    (354, 'IsEssential', 0, 0, 0),
    (358, 'IsPlayerMovingIntoNewSpace', 0, 0, 0),
    (359, 'GetInCurrentLocation', 2, 0, 0),
    (360, 'GetInCurrentLocationAlias', 0, 0, 0),
    (361, 'GetTimeDead', 0, 0, 0),
    (362, 'HasLinkedRef', 2, 0, 0),
    (365, 'IsChild', 0, 0, 0),
    (366, 'GetStolenItemValueNoCrime', 2, 0, 0),
    (367, 'GetLastPlayerAction', 0, 0, 0),
    (368, 'IsPlayerActionActive', 1, 0, 0),
    (370, 'IsTalkingActivatorActor', 2, 0, 0),
    (372, 'IsInList', 2, 0, 0),
    (373, 'GetStolenItemValue', 2, 0, 0),
    (375, 'GetCrimeGoldViolent', 2, 0, 0),
    (376, 'GetCrimeGoldNonviolent', 2, 0, 0),
    (378, 'IsOwnedBy', 2, 0, 0),
    (380, 'GetCommandDistance', 0, 0, 0),
    (381, 'GetCommandLocationDistance', 0, 0, 0),
    (390, 'GetHitLocation', 0, 0, 0),
    (391, 'IsPC1stPerson', 0, 0, 0),
    (396, 'GetCauseofDeath', 0, 0, 0),
    (397, 'IsLimbGone', 1, 0, 0),
    (398, 'IsWeaponInList', 2, 0, 0),
    (402, 'IsBribedbyPlayer', 0, 0, 0),
    (403, 'GetRelationshipRank', 2, 0, 0),
    (407, 'GetVATSValue', 1, 1, 0),
    (408, 'IsKiller', 2, 0, 0),
    (409, 'IsKillerObject', 2, 0, 0),
    (410, 'GetFactionCombatReaction', 2, 2, 0),
    (414, 'Exists', 2, 0, 0),
    (415, 'GetGroupMemberCount', 0, 0, 0),
    (416, 'GetGroupTargetCount', 0, 0, 0),
    (426, 'GetIsVoiceType', 2, 0, 0),
    (427, 'GetPlantedExplosive', 0, 0, 0),
    (429, 'IsScenePackageRunning', 0, 0, 0),
    (430, 'GetHealthPercentage', 0, 0, 0),
    (432, 'GetIsObjectType', 2, 0, 0),
    (434, 'PlayerVisualDetection', 0, 0, 0),
    (435, 'PlayerAudioDetection', 0, 0, 0),
    (437, 'GetIsCreatureType', 1, 0, 0),
    (438, 'HasKey', 2, 0, 0),
    (439, 'IsFurnitureEntryType', 0, 0, 0),
    (444, 'GetInCurrentLocationFormList', 2, 0, 0),
    (445, 'GetInZone', 2, 0, 0),
    (446, 'GetVelocity', 0, 0, 0),
    (447, 'GetGraphVariableFloat', 0, 0, 0),
    (448, 'HasPerk', 2, 0, 0),
    (449, 'GetFactionRelation', 2, 0, 0),
    (450, 'IsLastIdlePlayed', 2, 0, 0),
    (453, 'GetPlayerTeammate', 0, 0, 0),
    (454, 'GetPlayerTeammateCount', 0, 0, 0),
    (458, 'GetActorCrimePlayerEnemy', 0, 0, 0),
    (459, 'GetCrimeGold', 2, 0, 0),
    (463, 'IsPlayerGrabbedRef', 2, 0, 0),
    (465, 'GetKeywordItemCount', 2, 0, 0),
    (470, 'GetDestructionStage', 0, 0, 0),
    (473, 'GetIsAlignment', 1, 0, 0),
    (476, 'IsProtected', 0, 0, 0),
    (477, 'GetThreatRatio', 2, 0, 0),
    (479, 'GetIsUsedItemEquipType', 1, 0, 0),
    (483, 'GetPlayerActivated', 0, 0, 0),
    (485, 'GetFullyEnabledActorsInHigh', 0, 0, 0),
    (487, 'IsCarryable', 0, 0, 0),
    (488, 'GetConcussed', 0, 0, 0),
    (491, 'GetMapMarkerVisible', 0, 0, 0),
    (493, 'PlayerKnows', 2, 0, 0),
    (494, 'GetPermanentValue', 2, 0, 0),
    (495, 'GetKillingBlowLimb', 0, 0, 0),
    (497, 'CanPayCrimeGold', 2, 0, 0),
    (499, 'GetDaysInJail', 0, 0, 0),
    (500, 'EPAlchemyGetMakingPoison', 0, 0, 0),
    (501, 'EPAlchemyEffectHasKeyword', 2, 0, 0),
    (503, 'GetAllowWorldInteractions', 0, 0, 0),
    (506, 'DialogueGetAv', 2, 0, 0),
    (507, 'DialogueHasPerk', 2, 0, 0),
    (508, 'GetLastHitCritical', 0, 0, 0),
    (510, 'DialogueGetItemCount', 2, 0, 0),
    (511, 'LastCrippledCondition', 2, 0, 0),
    (512, 'HasSharedPowerGrid', 2, 0, 0),
    (513, 'IsCombatTarget', 2, 0, 0),
    (515, 'GetVATSRightAreaFree', 2, 0, 0),
    (516, 'GetVATSLeftAreaFree', 2, 0, 0),
    (517, 'GetVATSBackAreaFree', 2, 0, 0),
    (518, 'GetVATSFrontAreaFree', 2, 0, 0),
    (519, 'GetIsLockBroken', 0, 0, 0),
    (520, 'IsPS3', 0, 0, 0),
    (521, 'IsWindowsPC', 0, 0, 0),
    (522, 'GetVATSRightTargetVisible', 2, 0, 0),
    (523, 'GetVATSLeftTargetVisible', 2, 0, 0),
    (524, 'GetVATSBackTargetVisible', 2, 0, 0),
    (525, 'GetVATSFrontTargetVisible', 2, 0, 0),
    (528, 'IsInCriticalStage', 0, 0, 0),
    (530, 'GetXPForNextLevel', 0, 0, 0),
    (533, 'GetInfamy', 2, 0, 0),
    (534, 'GetInfamyViolent', 2, 0, 0),
    (535, 'GetInfamyNonViolent', 2, 0, 0),
    (536, 'GetTypeCommandPerforming', 0, 0, 0),
    (543, 'GetQuestCompleted', 2, 0, 0),
    (544, 'GetSpeechChallengeSuccessLevel', 0, 0, 0),
    (547, 'IsGoreDisabled', 0, 0, 0),
    (550, 'IsSceneActionComplete', 2, 2, 0),
    (552, 'GetSpellUsageNum', 2, 0, 0),
    (554, 'GetActorsInHigh', 0, 0, 0),
    (555, 'HasLoaded3D', 0, 0, 0),
    (560, 'HasKeyword', 2, 0, 0),
    (561, 'HasRefType', 0, 0, 0),
    (562, 'LocationHasKeyword', 2, 0, 0),
    (563, 'LocationHasRefType', 0, 0, 0),
    (565, 'GetIsEditorLocation', 2, 0, 0),
    (566, 'GetIsAliasRef', 0, 0, 0),
    (567, 'GetIsEditorLocationAlias', 0, 0, 0),
    (568, 'IsSprinting', 0, 0, 0),
    (569, 'IsBlocking', 0, 0, 0),
    (570, 'HasEquippedSpell', 0, 0, 0),
    (571, 'GetCurrentCastingType', 0, 0, 0),
    (572, 'GetCurrentDeliveryType', 0, 0, 0),
    (574, 'GetAttackState', 0, 0, 0),
    (576, 'GetEventData', 0, 0, 0),
    (577, 'IsCloserToAThanB', 2, 2, 0),
    (578, 'LevelMinusPCLevel', 0, 0, 0),
    (580, 'IsBleedingOut', 0, 0, 0),
    (584, 'GetRelativeAngle', 2, 0, 0),
    (589, 'GetMovementDirection', 0, 0, 0),
    (590, 'IsInScene', 0, 0, 0),
    (591, 'GetRefTypeDeadCount', 2, 0, 0),
    (592, 'GetRefTypeAliveCount', 2, 0, 0),
    (594, 'GetIsFlying', 0, 0, 0),
    (595, 'IsCurrentSpell', 2, 0, 0),
    (596, 'SpellHasKeyword', 0, 2, 0),
    (597, 'GetEquippedItemType', 0, 0, 0),
    (598, 'GetLocationAliasCleared', 0, 0, 0),
    (600, 'GetLocationAliasRefTypeDeadCount', 0, 0, 0),
    (601, 'GetLocationAliasRefTypeAliveCount', 0, 0, 0),
    (602, 'IsWardState', 0, 0, 0),
    (603, 'IsInSameCurrentLocationAsRef', 2, 2, 0),
    (604, 'IsInSameCurrentLocationAsRefAlias', 0, 2, 0),
    (605, 'LocationAliasIsLocation', 0, 2, 0),
    (606, 'GetKeywordDataForLocation', 2, 2, 0),
    (608, 'GetKeywordDataForAlias', 0, 2, 0),
    (610, 'LocationAliasHasKeyword', 0, 2, 0),
    (611, 'IsNullPackageData', 0, 0, 0),
    (612, 'GetNumericPackageData', 1, 0, 0),
    (613, 'IsPlayerRadioOn', 0, 0, 0),
    (614, 'GetPlayerRadioFrequency', 0, 0, 0),
    (615, 'GetHighestRelationshipRank', 0, 0, 0),
    (616, 'GetLowestRelationshipRank', 0, 0, 0),
    (617, 'HasAssociationTypeAny', 0, 0, 0),
    (618, 'HasFamilyRelationshipAny', 0, 0, 0),
    (619, 'GetPathingTargetOffset', 0, 0, 0),
    (620, 'GetPathingTargetAngleOffset', 0, 0, 0),
    (621, 'GetPathingTargetSpeed', 0, 0, 0),
    (622, 'GetPathingTargetSpeedAngle', 0, 0, 0),
    (623, 'GetMovementSpeed', 0, 0, 0),
    (624, 'GetInContainer', 2, 0, 0),
    (625, 'IsLocationLoaded', 2, 0, 0),
    (626, 'IsLocationAliasLoaded', 0, 0, 0),
    (627, 'IsDualCasting', 0, 0, 0),
    (629, 'GetVMQuestVariable', 2, 0, 0),
    (630, 'GetCombatAudioDetection', 0, 0, 0),
    (631, 'GetCombatVisualDetection', 0, 0, 0),
    (632, 'IsCasting', 0, 0, 0),
    (633, 'GetFlyingState', 0, 0, 0),
    (635, 'IsInFavorState', 0, 0, 0),
    (636, 'HasTwoHandedWeaponEquipped', 0, 0, 0),
    (637, 'IsFurnitureExitType', 0, 0, 0),
    (638, 'IsInFriendStatewithPlayer', 0, 0, 0),
    (639, 'GetWithinDistance', 2, 3, 0),
    (640, 'GetValuePercent', 2, 0, 0),
    (641, 'IsUnique', 0, 0, 0),
    (642, 'GetLastBumpDirection', 0, 0, 0),
    (644, 'GetInfoChallangeSuccess', 0, 0, 0),
    (645, 'GetIsInjured', 0, 0, 0),
    (646, 'GetIsCrashLandRequest', 0, 0, 0),
    (647, 'GetIsHastyLandRequest', 0, 0, 0),
    (650, 'IsLinkedTo', 2, 2, 0),
    (651, 'GetKeywordDataForCurrentLocation', 2, 0, 0),
    (652, 'GetInSharedCrimeFaction', 2, 0, 0),
    (654, 'GetBribeSuccess', 0, 0, 0),
    (655, 'GetIntimidateSuccess', 0, 0, 0),
    (656, 'GetArrestedState', 0, 0, 0),
    (657, 'GetArrestingActor', 0, 0, 0),
    (659, 'HasVMScript', 0, 0, 0),
    (660, 'GetVMScriptVariable', 0, 0, 0),
    (661, 'GetWorkshopResourceDamage', 2, 0, 0),
    (664, 'HasValidRumorTopic', 2, 0, 0),
    (672, 'IsAttacking', 0, 0, 0),
    (673, 'IsPowerAttacking', 0, 0, 0),
    (674, 'IsLastHostileActor', 0, 0, 0),
    (675, 'GetGraphVariableInt', 0, 0, 0),
    (678, 'ShouldAttackKill', 2, 0, 0),
    (680, 'GetActivationHeight', 0, 0, 0),
    (682, 'WornHasKeyword', 2, 0, 0),
    (683, 'GetPathingCurrentSpeed', 0, 0, 0),
    (684, 'GetPathingCurrentSpeedAngle', 0, 0, 0),
    (691, 'GetWorkshopObjectCount', 2, 0, 0),
    (693, 'EPMagic_SpellHasKeyword', 2, 0, 0),
    (694, 'GetNoBleedoutRecovery', 0, 0, 0),
    (696, 'EPMagic_SpellHasSkill', 2, 0, 0),
    (697, 'IsAttackType', 2, 0, 0),
    (698, 'IsAllowedToFly', 0, 0, 0),
    (699, 'HasMagicEffectKeyword', 2, 0, 0),
    (700, 'IsCommandedActor', 0, 0, 0),
    (701, 'IsStaggered', 0, 0, 0),
    (702, 'IsRecoiling', 0, 0, 0),
    (703, 'HasScopeWeaponEquipped', 0, 0, 0),
    (704, 'IsPathing', 0, 0, 0),
    (705, 'GetShouldHelp', 2, 0, 0),
    (706, 'HasBoundWeaponEquipped', 0, 0, 0),
    (707, 'GetCombatTargetHasKeyword', 2, 0, 0),
    (709, 'GetCombatGroupMemberCount', 0, 0, 0),
    (710, 'IsIgnoringCombat', 0, 0, 0),
    (711, 'GetLightLevel', 0, 0, 0),
    (713, 'SpellHasCastingPerk', 2, 0, 0),
    (714, 'IsBeingRidden', 0, 0, 0),
    (715, 'IsUndead', 0, 0, 0),
    (716, 'GetRealHoursPassed', 0, 0, 0),
    (718, 'IsUnlockedDoor', 0, 0, 0),
    (719, 'IsHostileToActor', 2, 0, 0),
    (720, 'GetTargetHeight', 2, 0, 0),
    (721, 'IsPoison', 0, 0, 0),
    (722, 'WornApparelHasKeywordCount', 2, 0, 0),
    (723, 'GetItemHealthPercent', 0, 0, 0),
    (724, 'EffectWasDualCast', 0, 0, 0),
    (725, 'GetKnockStateEnum', 0, 0, 0),
    (726, 'DoesNotExist', 0, 0, 0),
    (728, 'GetPlayerWalkAwayFromDialogueScene', 0, 0, 0),
    (729, 'GetActorStance', 0, 0, 0),
    (734, 'CanProduceForWorkshop', 0, 0, 0),
    (735, 'CanFlyHere', 0, 0, 0),
    (736, 'EPIsDamageType', 1, 0, 0),
    (738, 'GetActorGunState', 0, 0, 0),
    (739, 'GetVoiceLineLength', 0, 0, 0),
    (741, 'ObjectTemplateItem_HasKeyword', 2, 0, 0),
    (742, 'ObjectTemplateItem_HasUniqueKeyword', 2, 0, 0),
    (743, 'ObjectTemplateItem_GetLevel', 0, 0, 0),
    (744, 'MovementIdleMatches', 0, 0, 0),
    (745, 'GetActionData', 0, 0, 0),
    (746, 'GetActionDataShort', 1, 0, 0),
    (747, 'GetActionDataByte', 1, 0, 0),
    (748, 'GetActionDataFlag', 1, 0, 0),
    (749, 'ModdedItemHasKeyword', 2, 0, 0),
    (750, 'GetAngryWithPlayer', 0, 0, 0),
    (751, 'IsCameraUnderWater', 0, 0, 0),
    (753, 'IsActorRefOwner', 2, 0, 0),
    (754, 'HasActorRefOwner', 2, 0, 0),
    (756, 'GetLoadedAmmoCount', 0, 0, 0),
    (757, 'IsTimeSpanSunrise', 0, 0, 0),
    (758, 'IsTimeSpanMorning', 0, 0, 0),
    (759, 'IsTimeSpanAfternoon', 0, 0, 0),
    (760, 'IsTimeSpanEvening', 0, 0, 0),
    (761, 'IsTimeSpanSunset', 0, 0, 0),
    (762, 'IsTimeSpanNight', 0, 0, 0),
    (763, 'IsTimeSpanMidnight', 0, 0, 0),
    (764, 'IsTimeSpanAnyDay', 0, 0, 0),
    (765, 'IsTimeSpanAnyNight', 0, 0, 0),
    (766, 'CurrentFurnitureHasKeyword', 2, 0, 0),
    (767, 'GetWeaponEquipIndex', 0, 0, 0),
    (769, 'IsOverEncumbered', 0, 0, 0),
    (770, 'IsPackageRequestingBlockedIdles', 0, 0, 0),
    (771, 'GetActionDataInt', 0, 0, 0),
    (772, 'GetVATSRightMinusLeftAreaFree', 2, 0, 0),
    (773, 'GetInIronSights', 2, 0, 0),
    (774, 'GetActorStaggerDirection', 0, 0, 0),
    (775, 'GetActorStaggerMagnitude', 0, 0, 0),
    (776, 'WornCoversBipedSlot', 1, 0, 0),
    (777, 'GetInventoryValue', 0, 0, 0),
    (778, 'IsPlayerInConversation', 0, 0, 0),
    (779, 'IsInDialogueCamera', 0, 0, 0),
    (780, 'IsMyDialogueTargetPlayer', 0, 0, 0),
    (781, 'IsMyDialogueTargetActor', 0, 0, 0),
    (782, 'GetMyDialogueTargetDistance', 0, 0, 0),
    (783, 'IsSeatOccupied', 2, 0, 0),
    (784, 'IsPlayerRiding', 0, 0, 0),
    (785, 'IsTryingEventCamera', 0, 0, 0),
    (786, 'UseLeftSideCamera', 0, 0, 0),
    (787, 'GetNoteType', 0, 0, 0),
    (788, 'LocationHasPlayerOwnedWorkshop', 0, 0, 0),
    (789, 'IsStartingAction', 0, 0, 0),
    (790, 'IsMidAction', 0, 0, 0),
    (791, 'IsWeaponChargeAttack', 0, 0, 0),
    (792, 'IsInWorkshopMode', 0, 0, 0),
    (793, 'IsWeaponChargingHoldAttack', 0, 0, 0),
    (794, 'IsEncounterAbovePlayerLevel', 0, 0, 0),
    (795, 'IsMeleeAttacking', 0, 0, 0),
    (796, 'GetVATSQueuedTargetsUnique', 0, 0, 0),
    (797, 'GetCurrentLocationCleared', 0, 0, 0),
    (798, 'IsPowered', 0, 0, 0),
    (799, 'GetTransmitterDistance', 0, 0, 0),
    (800, 'GetCameraPlaybackTime', 0, 0, 0),
    (801, 'IsInWater', 0, 0, 0),
    (802, 'GetWithinActivateDistance', 2, 0, 0),
    (803, 'IsUnderWater', 0, 0, 0),
    (804, 'IsInSameSpace', 2, 0, 0),
    (805, 'LocationAllowsReset', 0, 0, 0),
    (806, 'GetVATSBackRightAreaFree', 2, 0, 0),
    (807, 'GetVATSBackLeftAreaFree', 2, 0, 0),
    (808, 'GetVATSBackRightTargetVisible', 2, 0, 0),
    (809, 'GetVATSBackLeftTargetVisible', 2, 0, 0),
    (810, 'GetVATSTargetLimbVisible', 2, 0, 0),
    (811, 'IsPlayerListening', 3, 0, 0),
    (812, 'GetPathingRequestedQuickTurn', 0, 0, 0),
    (813, 'EPIsCalculatingBaseDamage', 0, 0, 0),
    (814, 'GetReanimating', 0, 0, 0),
    (817, 'IsInRobotWorkbench', 0, 0, 0),
    )

allConditions = set(entry[0] for entry in conditionFunctionData)
fid1Conditions = set(entry[0] for entry in conditionFunctionData if entry[2] == 2)
fid2Conditions = set(entry[0] for entry in conditionFunctionData if entry[3] == 2)
# Skip 3 and 4 because it needs to be set per runOn
fid5Conditions = set(entry[0] for entry in conditionFunctionData if entry[4] == 2)

#--List of GMST's in the main plugin (Fallout4.esm) that have 0x00000000
#  as the form id.  Any GMST as such needs it Editor Id listed here.
gmstEids = [
    ## TODO: Initial inspection did not seem to have any null FormID GMST's,
    ## double check before enabling the GMST Tweaker
    ]

"""
GLOB record tweaks used by patcher.patchers.multitweak_settings.GmstTweaker

Each entry is a tuple in the following format:
  (DisplayText, MouseoverText, GLOB EditorID, Option1, Option2, ..., OptionN)
  -EditorID can be a plain string, or a tuple of multiple Editor IDs.  If
  it's a tuple, then Value (below) must be a tuple of equal length, providing
  values for each GLOB
Each Option is a tuple:
  (DisplayText, Value)
  - If you enclose DisplayText in brackets like this: _(u'[Default]'),
  then the patcher will treat this option as the default value.
  - If you use _(u'Custom') as the entry, the patcher will bring up a number
  input dialog

To make a tweak Enabled by Default, enclose the tuple entry for the tweak in
a list, and make a dictionary as the second list item with {'defaultEnabled
':True}. See the UOP Vampire face fix for an example of this (in the GMST
Tweaks)
"""
GlobalsTweaks = list()

"""
GMST record tweaks used by patcher.patchers.multitweak_settings.GmstTweaker

Each entry is a tuple in the following format:
  (DisplayText, MouseoverText, GMST EditorID, Option1, Option2, ..., OptionN)
  - EditorID can be a plain string, or a tuple of multiple Editor IDs. If
  it's a tuple, then Value (below) must be a tuple of equal length, providing
  values for each GMST
Each Option is a tuple:
  (DisplayText, Value)
  - If you enclose DisplayText in brackets like this: _(u'[Default]'),
  then the patcher will treat this option as the default value.
  - If you use _(u'Custom') as the entry, the patcher will bring up a number
  input dialog

To make a tweak Enabled by Default, enclose the tuple entry for the tweak in
a list, and make a dictionary as the second list item with {'defaultEnabled
':True}. See the UOP Vampire facefix for an example of this (in the GMST
Tweaks)
"""
GmstTweaks = list()

#------------------------------------------------------------------------------
# ListsMerger
#------------------------------------------------------------------------------
listTypes = ('LVLI','LVLN',)
#------------------------------------------------------------------------------
# NamesPatcher
#------------------------------------------------------------------------------
# remaining to add: 'PERK', 'RACE',
namesTypes = set()
#------------------------------------------------------------------------------
# ItemPrices Patcher
#------------------------------------------------------------------------------
pricesTypes = dict()

#------------------------------------------------------------------------------
# StatsImporter
#------------------------------------------------------------------------------
statsTypes = dict()
statsHeaders = tuple()

#------------------------------------------------------------------------------
# SoundPatcher
#------------------------------------------------------------------------------
# Needs longs in SoundPatcher
soundsLongsTypes = set() # initialize with literal
soundsTypes = {}
#------------------------------------------------------------------------------
# CellImporter
#------------------------------------------------------------------------------
cellAutoKeys = set()
cellRecAttrs = {}
cellRecFlags = {}
#------------------------------------------------------------------------------
# GraphicsPatcher
#------------------------------------------------------------------------------
graphicsLongsTypes = set() # initialize with literal
graphicsTypes = {}
graphicsFidTypes = {}
graphicsModelAttrs = ()
#------------------------------------------------------------------------------
# Inventory Patcher
#------------------------------------------------------------------------------
inventoryTypes = ('NPC_','CONT',)

# Record type to name dictionary
record_type_name = {}

# xEdit menu string and key for expert setting
xEdit_expert = (_(u'FO4Edit Expert'), 'fo4View.iKnowWhatImDoing')
